export enum PropertyEvents {
  PROPERTY_CREATED = 'PROPERTY_CREATED',
  PROPERTY_UPDATED = 'PROPERTY_UPDATED',
  PROPERTY_DELETED = 'PROPERTY_DELETED',
  PROPERTY_LOGGED_IN = 'PROPERTY_LOGGED_IN',
  PROPERTY_EMAIL_HAS_CHANGED = 'PROPERTY_EMAIL_HAS_CHANGED',
}
